/**
 * Common names for tree genera, used to describe Jev's genus labels ("Birke" -> Betula)
 * and for the rule based fallback. Botanical knowledge, not city specific.
 */
export const GENUS_NAMES: Record<string, { de: string[]; en: string[]; hint?: string }> = {
  Abies: { de: ["Tanne"], en: ["fir"] },
  Acer: { de: ["Ahorn", "Bergahorn", "Spitzahorn", "Feldahorn"], en: ["maple", "sycamore"] },
  Aesculus: { de: ["Rosskastanie", "Kastanie"], en: ["horse chestnut", "buckeye", "conker tree"], hint: "plain German 'Kastanie' almost always means this genus" },
  Ailanthus: { de: ["Götterbaum"], en: ["tree of heaven"] },
  Alnus: { de: ["Erle"], en: ["alder"] },
  Amelanchier: { de: ["Felsenbirne"], en: ["serviceberry", "juneberry"] },
  Betula: { de: ["Birke"], en: ["birch"] },
  Carpinus: { de: ["Hainbuche", "Weißbuche"], en: ["hornbeam"] },
  Castanea: { de: ["Esskastanie", "Edelkastanie", "Marone"], en: ["sweet chestnut"], hint: "only when Ess-/Edelkastanie or sweet chestnut is said explicitly" },
  Catalpa: { de: ["Trompetenbaum"], en: ["catalpa"] },
  Cedrus: { de: ["Zeder"], en: ["cedar"] },
  Celtis: { de: ["Zürgelbaum"], en: ["hackberry"] },
  Cercidiphyllum: { de: ["Katsurabaum", "Lebkuchenbaum"], en: ["katsura"] },
  Chamaecyparis: { de: ["Scheinzypresse"], en: ["false cypress"] },
  Cladrastis: { de: ["Gelbholz"], en: ["yellowwood"] },
  Cornus: { de: ["Hartriegel", "Kornelkirsche"], en: ["dogwood"] },
  Corylus: { de: ["Hasel", "Baumhasel"], en: ["hazel", "turkish hazel"] },
  Crataegus: { de: ["Weißdorn", "Rotdorn"], en: ["hawthorn"] },
  Cryptomeria: { de: ["Sicheltanne"], en: ["japanese cedar"] },
  Davidia: { de: ["Taschentuchbaum"], en: ["dove tree", "handkerchief tree"] },
  Decaisnea: { de: ["Blauschote"], en: ["blue sausage fruit"] },
  Euonymus: { de: ["Pfaffenhütchen", "Spindelstrauch"], en: ["spindle"] },
  Fagus: { de: ["Buche", "Rotbuche", "Blutbuche"], en: ["beech"] },
  Fraxinus: { de: ["Esche"], en: ["ash"] },
  Ginkgo: { de: ["Ginkgo", "Fächerblattbaum"], en: ["ginkgo", "maidenhair tree"] },
  Gleditsia: { de: ["Gleditschie", "Lederhülsenbaum"], en: ["honey locust"] },
  Ilex: { de: ["Stechpalme", "Ilex"], en: ["holly"] },
  Juglans: { de: ["Walnuss", "Nussbaum"], en: ["walnut"] },
  Juniperus: { de: ["Wacholder"], en: ["juniper"] },
  Koelreuteria: { de: ["Blasenbaum"], en: ["golden rain tree"] },
  Laburnum: { de: ["Goldregen"], en: ["laburnum", "golden chain"] },
  Larix: { de: ["Lärche"], en: ["larch"] },
  Liquidambar: { de: ["Amberbaum"], en: ["sweetgum"] },
  Liriodendron: { de: ["Tulpenbaum"], en: ["tulip tree"] },
  Magnolia: { de: ["Magnolie"], en: ["magnolia"] },
  Malus: { de: ["Apfel", "Zierapfel", "Apfelbaum"], en: ["apple", "crabapple"] },
  Mespilus: { de: ["Mispel"], en: ["medlar"] },
  Metasequoia: { de: ["Urweltmammutbaum"], en: ["dawn redwood"] },
  Nyssa: { de: ["Tupelobaum"], en: ["tupelo"] },
  Parrotia: { de: ["Eisenholzbaum", "Parrotie"], en: ["persian ironwood"] },
  Paulownia: { de: ["Blauglockenbaum"], en: ["empress tree", "paulownia"] },
  Picea: { de: ["Fichte"], en: ["spruce"] },
  Pinus: { de: ["Kiefer", "Föhre"], en: ["pine"] },
  Platanus: { de: ["Platane"], en: ["plane tree", "sycamore (us)"] },
  Populus: { de: ["Pappel", "Espe", "Zitterpappel"], en: ["poplar", "aspen"] },
  Prunus: { de: ["Kirsche", "Zierkirsche", "Traubenkirsche", "Pflaume"], en: ["cherry", "plum"] },
  Pseudotsuga: { de: ["Douglasie"], en: ["douglas fir"] },
  Pterocarya: { de: ["Flügelnuss"], en: ["wingnut"] },
  Pyrus: { de: ["Birne", "Zierbirne", "Birnbaum"], en: ["pear"] },
  Quercus: { de: ["Eiche", "Stieleiche", "Traubeneiche", "Roteiche"], en: ["oak"] },
  Robinia: { de: ["Robinie", "Scheinakazie", "Akazie"], en: ["black locust", "robinia"] },
  Salix: { de: ["Weide", "Trauerweide"], en: ["willow"] },
  Sambucus: { de: ["Holunder"], en: ["elder"] },
  Sequoiadendron: { de: ["Mammutbaum", "Riesenmammutbaum"], en: ["giant sequoia"] },
  Sophora: { de: ["Schnurbaum"], en: ["pagoda tree"] },
  Sorbus: { de: ["Eberesche", "Vogelbeere", "Mehlbeere", "Elsbeere"], en: ["rowan", "whitebeam", "mountain ash"] },
  Taxodium: { de: ["Sumpfzypresse"], en: ["bald cypress"] },
  Taxus: { de: ["Eibe"], en: ["yew"] },
  Thuja: { de: ["Lebensbaum", "Thuja"], en: ["arborvitae", "thuja"] },
  Tilia: { de: ["Linde", "Winterlinde", "Sommerlinde"], en: ["linden", "lime tree", "basswood"] },
  Tsuga: { de: ["Hemlocktanne"], en: ["hemlock"] },
  Ulmus: { de: ["Ulme", "Rüster"], en: ["elm"] },
  Viburnum: { de: ["Schneeball"], en: ["viburnum"] },
  Zelkova: { de: ["Zelkove"], en: ["zelkova"] },
};

export const germanName = (genus: string) => GENUS_NAMES[genus]?.de[0] ?? genus;
export const englishName = (genus: string) => GENUS_NAMES[genus]?.en[0] ?? genus;
